version: "3.7"
services:
  register:
    image: docker.jahport.com/cloud-register-ci:1.0
    deploy:
      mode: replicated
      replicas: 1
      resources: 
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
      restart_policy:
        condition: on-failure
    ports:
      - "10001:10001"
    networks:
      - network_jahport
  config:
    image: docker.jahport.com/cloud-config:1.0.0
    depends_on:
      - register
    deploy:
      mode: replicated
      replicas: 1
      resources: 
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
      restart_policy:
        condition: on-failure
    ports:
      - "10002:10002"
    networks:
      - network_jahport
networks:
  network_jahport:
    external: true
